# Exported from Render on 2024-08-29T03:46:00Z
services:
- type: web
  name: parvoz
  runtime: python
  repo: https://github.com/Abduvohid26/Recipe
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python manage.py runserver 8000
version: "1"
